/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyFirstComponente {
        "name": string;
    }
    interface MyFirstComponentes {
        "name": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyFirstComponenteElement extends Components.MyFirstComponente, HTMLStencilElement {
    }
    var HTMLMyFirstComponenteElement: {
        prototype: HTMLMyFirstComponenteElement;
        new (): HTMLMyFirstComponenteElement;
    };
    interface HTMLMyFirstComponentesElement extends Components.MyFirstComponentes, HTMLStencilElement {
    }
    var HTMLMyFirstComponentesElement: {
        prototype: HTMLMyFirstComponentesElement;
        new (): HTMLMyFirstComponentesElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-first-componente": HTMLMyFirstComponenteElement;
        "my-first-componentes": HTMLMyFirstComponentesElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyFirstComponente {
        "name"?: string;
    }
    interface MyFirstComponentes {
        "name"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-first-componente": MyFirstComponente;
        "my-first-componentes": MyFirstComponentes;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-first-componente": LocalJSX.MyFirstComponente & JSXBase.HTMLAttributes<HTMLMyFirstComponenteElement>;
            "my-first-componentes": LocalJSX.MyFirstComponentes & JSXBase.HTMLAttributes<HTMLMyFirstComponentesElement>;
        }
    }
}
